### ISSUE TITLE
Wrong constant name

### ISSUE THREAD

**Issue by emil-nasso** [xp-forge/nsca#1]
The constructor in `NscaClient`uses a constant the is not defined:
https://github.com/xp-forge/nsca/blob/master/src/main/php/org/nagios/nsca/NscaClient.class.php#L62

The constant should be called: `NscaProtocol::CRYPT_XOR` as can be seen here: https://github.com/xp-forge/nsca/blob/master/src/main/php/org/nagios/nsca/NscaProtocol.class.php#L13

**Comment by emil-nasso** [comment]
See PR #2

**Comment by thekid** [comment]
Shipped in https://github.com/xp-forge/nsca/releases/tag/v5.1.1
